fix: checkout before using yarn.lock in js-lint
The issue came up when trying to use a yarn.lock, when there was none.

/usr/local/bin/yarn cache dir
/home/runner/.cache/yarn/v6
Error: Dependencies lock file is not found in /home/runner/work/webpacker/webpacker. Supported file patterns: yarn.lock