CI: use caching for JavaScript workflows  (#3167)
* build: use actions/setup-node@v2 with caching

This attempts to use the "cache: yarn" directive, as described in https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

* build: use cache: yarn in js-lint workflow

* fix: checkout before using yarn.lock in js-lint

The issue came up when trying to use a yarn.lock, when there was none.

/usr/local/bin/yarn cache dir
/home/runner/.cache/yarn/v6
Error: Dependencies lock file is not found in /home/runner/work/webpacker/webpacker. Supported file patterns: yarn.lock