Explicitly require Rails::Engine
When this gem is running inside a Rails engine to do a task such as
`app:assets:precompile` an error is thrown:

```
➜  rails-plugin git:(master) ✗ rake app:assets:precompile
Compiling…
Compilation failed:
/Users/kevindew/dev/webpacker/lib/webpacker/railtie.rb:6:in `<top (required)>': uninitialized constant Rails::Engine (NameError)
	from /Users/kevindew/dev/webpacker/lib/webpacker.rb:38:in `require'
	from /Users/kevindew/dev/webpacker/lib/webpacker.rb:38:in `<top (required)>'
	from /Users/kevindew/dev/rails-plugin/test/dummy/bin/webpack:13:in `require'
	from /Users/kevindew/dev/rails-plugin/test/dummy/bin/webpack:13:in `<main>'
```
Explicitly requiring rails/engine resolves this.